# Generated by Django 4.1.1 on 2022-10-08 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2022, 10, 8, 18, 10, 19, 195349))),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('lifestyle', models.CharField(choices=[('Healthy', 'Healthy'), ('Corporate', 'Corporate'), ('City', 'City'), ('Rural', 'Rural'), ('Nomadic', 'Nomadic')], max_length=10)),
                ('activity_level', models.CharField(choices=[('N', 'No exercise'), ('O', 'Occasional, light exercise'), ('R', 'Regular exercise and training'), ('D', 'Daily training')], max_length=10)),
                ('goal', models.CharField(blank=True, max_length=250)),
                ('frequency', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
            ],
        ),
    ]
