# Generated by Django 4.1.1 on 2022-10-07 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 7, 14, 2, 54, 921177)),
        ),
    ]
